version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: shop_postgres
    environment:
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_pass
      POSTGRES_DB: shop_db
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
